# Generated by Django 4.0.6 on 2022-07-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_remove_movie_imdb_link_alter_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
