# Generated by Django 4.0.6 on 2022-07-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_cinemahall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=70)),
                ('hall', models.CharField(max_length=30)),
            ],
        ),
    ]
