# Generated by Django 4.0.6 on 2022-07-22 09:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('cinema', models.CharField(blank=True, max_length=30, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1500)),
            ],
        ),
    ]
