# Generated by Django 4.0.6 on 2022-07-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_cinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.CharField(choices=[('O', 'Occupied'), ('E', 'Empty')], default='Empty', max_length=10)),
            ],
        ),
    ]
