# Generated by Django 4.0.6 on 2022-07-15 09:21

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Your phone number', max_length=31)),
                ('city', models.CharField(max_length=20)),
                ('cinema', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1500)),
            ],
        ),
        migrations.AlterField(
            model_name='seat',
            name='reservation',
            field=models.CharField(choices=[('O', 'Occupied'), ('E', 'Empty')], default='E', max_length=10),
        ),
    ]
