# Generated by Django 4.0.6 on 2022-07-20 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='seats',
            new_name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='reservation',
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='cinema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema'),
        ),
        migrations.AddField(
            model_name='seat',
            name='code',
            field=models.CharField(default='1A', max_length=4),
        ),
        migrations.AddField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall'),
        ),
        migrations.AddField(
            model_name='seat',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
