# Generated by Django 4.0.6 on 2022-07-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_rename_seats_cinemahall_number_of_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='cinema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='cinema.cinema'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.cinemahall'),
        ),
    ]
