# Generated by Django 4.0.6 on 2022-07-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_cinemahall_cinema_alter_seat_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='cinema.cinema'),
        ),
    ]
