# Generated by Django 4.0.6 on 2022-07-29 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_schedule_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='cinema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.movie'),
        ),
    ]
