# Generated by Django 4.0.6 on 2022-08-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_schedule_cinema_alter_schedule_movie'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('cinema', 'hall', 'playing_time'), name='unique_schedule'),
        ),
    ]
