# Generated by Django 4.0.6 on 2022-08-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_schedule_unique_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall'),
        ),
    ]
