# Generated by Django 4.0.6 on 2022-08-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_alter_schedule_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='cinema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='cinema.cinema'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='cinema.cinemahall'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='cinema.movie'),
        ),
    ]
