# Generated by Django 4.0.6 on 2022-08-08 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_schedule_cinema_alter_schedule_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='cinema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.movie'),
        ),
    ]
