# Generated by Django 4.0.6 on 2022-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeduser',
            name='name',
        ),
        migrations.AddField(
            model_name='subscribeduser',
            name='firstname',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='subscribeduser',
            name='lastname',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
