# Generated by Django 4.0.6 on 2022-08-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_subscribeduser_firstname_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribeduser',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_subscription'),
        ),
    ]
