# Generated by Django 4.0.6 on 2022-09-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_subscribeduser_unique_subscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribeduser',
            name='unique_subscription',
        ),
        migrations.AlterField(
            model_name='subscribeduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
