# Generated by Django 4.0.6 on 2022-08-02 17:45

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_alter_schedule_hall'),
        ('reservation', '0002_alter_reservation_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='details', chained_model_field='hall', on_delete=django.db.models.deletion.CASCADE, to='cinema.seat'),
        ),
    ]
