# Generated by Django 4.0.6 on 2022-08-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
